export const AirportPrefixes: { [key: string]: string } = {
    'AIR CANADA': "AC",
    'Air Transat': "AT",
    'PAL airlines': "PA",
    'Air Inuit': "AI",
    'Porter': "PO",
    'UNITED': "UN",
    'CANADIAN NORTH': "CN",
    'American Airlines': "AA",
    'Emirates': "EM",
    'arajet': "AR",
    'DELTA': "DE",
    'flair': "FL",
    'AIR ALGERIE': "AL",
    'TUNISAIR': "TU",
    'SWISS': "SW",
    'Austrian': "AU",
    'Air Saint-Pierre': "SP",
    'AIRFRANCE': "AF",
    'KLM': "KLM",
    'Lufthansa': "LU",
    'Royal Air MAroc(RAM)': "MA",
    'BRITISH AIRWAYS': "BA",
    'AeroMexico': "AM",
    'CopaAirlines': "CO",
    'Lynx': "LY",
    'SUNWING': "SNW",
    'QATAR': "QT",
    'RAM': "RAM",
    'Another': "",
    "": '',
}